spring.application.name=TryCook

# Nastavení H2 databáze
spring.datasource.url=jdbc:h2:mem:cookbookdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatické vytvo?ení tabulek podle entit
spring.jpa.hibernate.ddl-auto=update

# Zobrazení SQL dotaz? v konzoli (super pro debugging)
spring.jpa.show-sql=true

# Povolení H2 konzole v prohlí?e?i (na adrese localhost:8080/h2-console)
spring.h2.console.enabled=true
